### ISSUE TITLE
Migrate primary authoritative DNS for `hackclub.app` to nest's CoreDNS server

### ISSUE THREAD

**Issue by reesericci** [hackclub/dns#995]
## Problem

For nest, we stood up our own authoritative DNS server at 188.40.159.194 (ns.hackclub.app).

We would like to migrate hackclub.app to using this server instead of using `hackclub/dns`.

However we'd also like to continue using the Hack Club DNSimple as a secondary DNS server:

> Configure your zones with Secondary DNS having DNSimple acting as a secondary DNS. Zone transfers are done via AXFR with a primary server of your choice.

## What needs to be done

```[tasklist]
### Tasks
- [ ] Add glue record that sets `ns.hackclub.app` to `188.40.159.194`
- [ ] Set `hackclub.app` nameserver's to point to `ns.hackclub.app` first, and then `ns1.dnsimple.com` second
- [ ] [Configure secondary DNS for `hackclub.app` on DNSimple's side](https://support.dnsimple.com/articles/secondary-dns-dnsimple-as-secondary/)
- [ ] We add outgoing AXFR transfers to DNSimple
```

## Why this isn't a PR

This isn't a PR because it requires changes on the registrar side. 

An alternative could be to use NS records, but that creates another point of failure and is less efficient than just delegating directly.

 An NS record would mean that a client would have to ask DNSimple just to get pointed to our DNS server - an unnecessary hoop.

**Comment by reesericci** [comment]
Closes #980

**Comment by reesericci** [comment]
closes #980

**Comment by grymmy** [comment]
@reesericci Please implement the alternative PR-centric approach you mentioned, which would keep this work fully open and declarative, and also (I believe) protect us in a situation where we wanted to switch providers...  While there might be some minimal performance consideration as per what you mention, I have a feeling that careful attention to TTL's might mitigate this to a large degree...

If you feel that I have missed something here or feel that this path forward is unworkable, please re-assign this to me with rationale.  Assigning to you for now.

**Comment by reesericci** [comment]
The approach I outlined has no effect on whether we switch providers since we are running our own authoritative nameserver, and provides better reliability since we can still use DNSimple as a secondary.

The openness part is kind of irrelevant because the only thing that would be open is the NS record which delegates the entire domain to our server. Someone can still find out how the records are delegated anyways because if they do a standard recursive query they'll get pointed to our nameserver.

**Comment by grymmy** [comment]
@reesericci if this work is doable as a PR to hackclub/dns, then please author a PR to accomplish it - if not, please just justification as to why it is not possible - all I've heard from you re that is that you believe it is possible, so that leads me to believe that is the path you should go down

**Comment by reesericci** [comment]
My point is that while it is possible, it's not the best option for this type of change, and a PR here doesn't improve openness or declarative-ness. There are actually more benefits to doing it the way I outlined like using DNSimple as a secondary for reliability. I can make a PR however if absolutely necessary.

**Comment by grymmy** [comment]
@reesericci if you want me to review it and land it, I am telling you it is absolutely necessary to form it as a PR, and if that is impossible, then explain why and I can follow up.

**Comment by reesericci** [comment]
Just opened https://github.com/hackclub/dns/pull/999.

However, with this PR, there's no way we can use DNSimple as a secondary nameserver to improve reliability for us. There's also an extra point of failure in having to ask DNSimple before getting routed to us.

**Comment by grymmy** [comment]
@reesericci given it seems you opened a separate PR that achieves (unless I am mistaken) what you wanted to do here in this one, I am closing this PR now.  If you believe that this issue was closed in error, please reopen with justification.
